name: Build Godot Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Godot:
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        platform: [linux, windows]

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Build
        id: build
        uses: felix-schindler/build-godot-action@v1.6.1
        with:
          name: untitled-plant-game
          preset: ${{ matrix.platform }}
          debugMode: "false"

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Client - ${{ matrix.platform }}
          path: ${{ github.workspace }}/${{ steps.build.outputs.build }}
