name: Build Godot Project

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"
  pull_request:
    branches:
      - main

jobs:
  Godot:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform: [linux, windows, mac]

    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true

      - name: Build
        id: build
        uses: felix-schindler/build-godot-action@v2.0.0
        if: github.event.pull_request.draft == false
        with:
          name: untitled-plant-game
          preset: ${{ matrix.platform }}
          debugMode: "false"

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GH_REPO_TOKEN }}
        with:
          files: |
            build/untitled-plant-game.app.zip
            build/untitled-plant-game.exe
            build/untitled-plant-game.x86_64
